version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_screener_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production


#bash 
# Build and start both services
# run the code 'docker-compose up --build' 
